### PR TITLE
Start with the default theme

### PR DESCRIPTION
**Pull request by yanokwa**
Addresses #44

#### What is included in this PR?
Reverts the theme and header changes to the default and neutral color.

### CODE REVIEW

**Comment by wbrunette** [comment]
Does anybody who is "watching" the website have a preference on colors? Now would be the time to speak up.

**Comment by yanokwa** [comment]
@smoyth You had mentioned brown as not your favorite. 

My hope here is to settle on the most neutral of colors and then folks can propose different colors. White is neutral :)

**Comment by smoyth** [comment]
I don't remember saying that... I love brown! My comments were much harder to deal with than a color preference! Unless I'm forgetting something...

**Comment by lognaturel** [comment]
I think maybe @alxndrsn made a comment?

I like the white background. Buttons look disabled to me in gray so I'd tend to go for ODK blue or ODK green but that's a minor thing. The heading links could also be ODK blue, possibly. Regardless, I do like this more than the browns.

**Comment by yanokwa** [comment]
Agreed that the default my be a little too bland. I've switched to the `contrast` theme and added some a darker gray and blue. 

**front page**
screen shot 2018-05-03 at 15 07 05

**sub-page**
screen shot 2018-05-03 at 15 07 20

**Pull request merged**
