### PR TITLE
Rename ODK 2

### PR DESCRIPTION
**Pull request by yanokwa**
#### What is included in this PR?

4abbbe4
* Renamed ODK 1 to ODK in text
* Renamed ODK 2 to ODKX in text
* Prepended all ODKX tools with ODKX
   * Breaks anchor links, but seems fine since the page is so small
* Added "formerly ODK 2" when both projects are mentioned side by side
   * Did not add "formerly ODK 1" because that term isn't as widely used and it makes the sentence insane.
* Remove uses of "ODK" to describe project where it might be confusing. This includes footer.
* Fixed PMC/TSC headers and links.
* Reduced "TSC 1" and "TSC 2" language to make future rename easier
* Reduced "ODK TSC" language to prevent confusion about what TSC does what
* Renamed {odk1/odk2}.md pages to {odk1/odk2}.md 
   * Added redirects that should work, but we'll need to test this right after merge.
* Renamed TSC image folders to match page structure

fe796b0
* Added ODK Central since it's official now
* Renamed Sonatype's Central Repository to a more obvious (and non-conflicting name)

1555afd
* Moved to 4 person layout on TSC 1 images
* Fixed Tom's Github link
* Tightened up former members layout
* No hotlinking to images on the forum for robustness

#### What's remaining
https://github.com/opendatakit/docs will need a change to redirect odk2 to odkx. We should do that before merging.

### CODE REVIEW

**Comment by wbrunette** [comment]
Since TSC 2 prefers ODK X (with a space) it would be nice if the website used the official name which is "ODK X". As presented to the PMC, we prefer "ODK X" with a space but we realize people are going to type both ODK X and ODKX in the forums, etc. and there is no need to correct people (as I think we all agree that we will all recognize it as the same thing). I do feel like the correct name "ODK X" should be used on the website.

**Comment by yanokwa** [comment]
I don't think we decided space or no space at the PMC. In sending in this PR, I saw that there are a few problems with using the space as an "official name".

- Searching for `ODK X` will give results with `ODK XForms` and `ODK XLS`. You have to use quotes which most users won't know. It's going to hurt discoverability.
- URLs will require some separator that will different from name (`opendatakit.com/software/odk-x`) and visible and so people will use it in prose, further diluting search.
- Tags will require some separator that makes for a messy tag (`odkx-survey` feels better than `odk-x-survey`) on the forum.
- For both tags and URLs, you don't have a separator, but then your URL is different than the name, which isn't great.
- Tool grouping is a little less obvious. `ODK X Application Designer` could belong to the ODK suite whereas `ODKX Application Designer` doesn't. Clearer separation helps users.

Is there a public record of the TSC 2 discussion so interested parties (and future us) can get a sense of the various considerations of the above issues and any others? I'm an avid reader of the TSC 2 meeting notes, but it's not there.

**Comment by wbrunette** [comment]
@yanokwa makes fair points. Looking at the issues, I personally think 'ODK-X' is an improvement over the "ODK X". TSC 2 meets on Tuesday. Can we wait until after meeting to get an updated answer about preference? I would propose the choice be between "ODK-X" and "ODKX" (happy to raise the question at the meeting).  After that we can get quick confirmation from the PMC?

**Comment by yanokwa** [comment]
@wbrunette That approach sounds great to me.

**Comment by wbrunette** [comment]
Waylon

**Comment by yanokwa** [comment]
I've forced pushed the change to ODK-X based on the discussion the TSC 2 had.

**Comment by yanokwa** [comment]
We have approval from the PMC, so this change is going live!

**Pull request merged**
